#!/bin/sh
#
prog=bmplotg
usage="usage: $prog host pngoutput"
#
#	Use gnuplot to create a plot for machine "host"
#
#	This program will create files in the current directory.

case $# in
2)	host="$1";	shift;
	outpng="$1";	shift;;
*)	echo "$usage" 1>&2
	exit 1
esac

TMPDIR=${TMPDIR:-/var/tmp}
WRKDIR=${WRKDIR:-${TMPDIR}/${prog}}
mkdir -p $WRKDIR        || exit 100
rm -rf $WRKDIR/*

DIR=$HOME/BM/$host

if [ ! -d $DIR/db ]
then
	echo "$prog: `hostname -s`: dir '$DIR/raw' missing, aborted" 1>&2
	exit 2
fi

if [ -s "$DIR/Names" ]
then
	names="$DIR/Names"
else
	names=/dev/null
fi

(
cat  <<!EOF 
set timefmt "%Y%m%d_%H%M"
set xdata time
set format x "%a %H"
set border 3
set size 2,2
set xlabel "Date"
set ylabel "Temp"
set terminal postscript eps color 24
set output "$WRKDIR/bm.ps"

!EOF
	echo -n "plot "
	for sensor in `ls $DIR/db | egrep -v "RX|TX"`
	do
		display_name=`grep "^$sensor	" $names | sed 's/^.*	//'`
		if [ ! -n "$display_name" ]
		then
			display_name=`echo "$sensor" | sed 's/..:..:..:..://'`
		fi

		echo "\"$DIR/db/$sensor\" using 1:2 title \"$display_name\" with lines lw 8, \\"
	done
) >>$WRKDIR/gnuplot.in

gnuplot <$WRKDIR/gnuplot.in

convert $WRKDIR/bm.ps $outpng
