#!/bin/sh
#
prog=bmplotall
usage="usage: $prog [conf]"
#
#	Combine all the Broodminder data into a single plot for the web.

case $# in
0);;
*)	echo "$usage" 1>&2
	exit 1
esac

TMPDIR=${TMPDIR:-/var/tmp}
WRKDIR=${WRKDIR:-${TMPDIR}/${prog}}
mkdir -p $WRKDIR        || exit 100
rm -rf $WRKDIR/*

PLOTIN=$WRKDIR/gnuplot.in
PLOTLIST=$WRKDIR/plotlist

mkdir -p $PLOTLIST
rm -rf $PLOTLIST/*

cd $HOME/BM

aps=`ls -d */db | sed 's:/.*::'`	# names of apiaries that have useful data
for ap in $aps
do
	mkdir $PLOTLIST/$ap	|| exit 90
done

ls */db/* | 
awk -v FS=/ -v OFS='	' -v pldir=$PLOTLIST '
{	ap=$1
	device=$3
	fn = pldir "/" ap
	if (device ~ /TX|RX/) {
		sfn = fn "/IO"
		print "IO" >>sfn
		next
	}
	n = split(device, octets, ":")
	if (n != 6) {
		print "confused by '" $0 "', skipping" >"/dev/stderr"
		next
	}
	if (octets[4] == 43) {
		sfn = fn "/scale"
		print device >>sfn
		next
	}
	sfn = fn "/sensor"
	print device >>sfn
}'

plotcount=`ls $PLOTLIST/*/* | wc -l | tr -d ' '`
echo plot count $plotcount

plots=`(cd $PLOTLIST; ls */*)`
apswithdata=`echo "$plots" | cut -f1 -d/ | sort -u`

cat  <<!EOF >$PLOTIN
set timefmt "%Y%m%d_%H%M"
set xdata time
set format x "%a %H"
set border 3
set size 2,2
set terminal postscript eps color 24
set output "$WRKDIR/bm.ps"
set multiplot layout $plotcount,1 rowsfirst
!EOF

for ap in $apswithdata
do

	if [ -s "$ap/Names" ]
	then
		names="$ap/Names"
	else
		names=/dev/null
	fi

	if [ -s $PLOTLIST/$ap/scale ]
	then
		echo "plot "
		for device in `cat ls $ap/db | egrep -v "RX|TX"`
		do
			display_name=`grep "^$device	" $names | sed 's/^.*	//'`
			if [ ! -n "$display_name" ]
			then
				display_name=`echo "$device" | sed 's/..:..:..:..://'`
			fi
	
			echo "\"$DIR/db/$device\" using 1:3 title \"$display_name\" with lines lw 8, \\"
		done
	fi

	if [ -s $PLOTLIST/$ap/sensor ]
	then
		echo "plot "
		for device in `cat ls $ap/db | egrep -v "RX|TX"`
		do
			display_name=`grep "^$device	" $names | sed 's/^.*	//'`
			if [ ! -n "$display_name" ]
			then
				display_name=`echo "$device" | sed 's/..:..:..:..://'`
			fi
	
			echo "\"$DIR/db/$device\" using 1:2 title \"$display_name\" with lines lw 8, \\"
		done
	fi

	if [ -s $PLOTLIST/$ap/IO ]
	then
		echo "plot "
		for device in `cat ls $ap/db | egrep -v "RX|TX"`
		do
			display_name=`grep "^$device	" $names | sed 's/^.*	//'`
			if [ ! -n "$display_name" ]
			then
				display_name=`echo "$device" | sed 's/..:..:..:..://'`
			fi
	
			echo "\"$DIR/db/$device\" using 1:2 title \"$display_name\" with lines lw 8, \\"
		done
	fi

	for sensor in `ls $ap/db | egrep -v "RX|TX"`
	do
		echo "plot "
		display_name=`grep "^$sensor	" $names | sed 's/^.*	//'`
		if [ ! -n "$display_name" ]
		then
			display_name=`echo "$sensor" | sed 's/..:..:..:..://'`
		fi

		echo "\"$DIR/db/$sensor\" using 1:2 title \"$display_name\" with lines lw 8, \\"
	done
done

exit 13
set xlabel "Date"
set ylabel "Temp"



!EOF

gnuplot <$WRKDIR/gnuplot.in

convert $WRKDIR/bm.ps $outpng
