#!/bin/sh
#
prog=rpi_light
usage="$prog on|up|down|off"
#
#	Power up a (nearly) suspended RPi to activate the network
#	and do stuff.  These actions are reversed by rpi_powerdown.

case $# in
1)	;;
*)	echo "$usage" 1>&2
	exit 1
esac

LIGHT_FN=/sys/class/leds/led0/brightness

case "$1" in
up|on)	
	echo 0 >$LIGHT_FN
	;;
down|off)
	echo 1 >$LIGHT_FN
	;;
*)
	echo "$usage" 1>&2
	exit 2
esac
