#!/bin/sh
#
prog=BMfetch
usage="$prog [-t timeout]"
#
#	This is the data collection routine.
#	env variable POLLDIR contains the directory for the raw data

TIMEOUT=60

while [ $# -gt 0 ]
do
	case "$1" in
	-t)	shift; TIMEOUT="$1"; shift;;
	*)
		echo "$usage" 1>&2
		exit 1
	esac
done

case $# in
0)	;;
*)	echo "$usage" 1>&2
	exit 2
esac

if [ ! -n "$POLLDIR" ]
then
	echo "$prog: env POLLDIR missing, aborted" 1>&2
	exit 3
fi

if [ ! -d "$POLLDIR" ]
then
	mkdir -p "$POLLDIR" 	|| exit 3
fi

# fetch hive sensor and scale data using BT advertisement data

NOW=`date +%Y/%m/%d-%H:%M`
CMD="bmscan -t $TIMEOUT"

(	$CMD 2>/dev/null || (
		sudo hciconfig hci0 down; sudo hciconfig hci0 up;
		$CMD )
) >/tmp/new

# record network traffic, in case we care (cell access?)

now=`date +%Y%m%d_%H%M`
pktvol=`ifconfig | grep 'packets' | sort -k3,3n -k1,1 | tail -2`
wifisignal=`iwconfig wlan0 2>/dev/null |
		grep level |
		cut -f2,4 |
		sed 's/[A-Z][^=]*=//g' |
		awk '{print $1, $2}'
`

if [ -n "$wifisignal" ]
then
	wifisignal="	wifi $wifisignal"
fi

(	cat /tmp/new
	echo "$pktvol"
	if [ -n "$wifisignal" ]
	then
		echo "	wifi $wifisignal"
	fi
) > $POLLDIR/$now

rm -f /tmp/new


