#!/bin/sh
#
prog=BMpush
usage="$prog targethost"
#
#	push out all the unsent data using rsync to a target host, directory
#		BM/<thishostname>/raw

case $# in
1)	targethost="$1";	shift;;
*)
	echo "$usage" 1>&2
	exit 1
esac

ME=`hostname -s`
TARGETRAW="BM/$ME/raw"

if [ ! -n "$POLLDIR" ]
then
	echo "$prog: env POLLDIR missing, aborted" 1>&2
	exit 2
fi

if [ ! -s "$POLLDIR" ]
then
	echo "$prog: POLLDIR directory missing, aborted" 1>&2
	exit 3
fi

ssh $targethost "mkdir -p $TARGETRAW 2>/dev/null"

(cd "$POLLDIR"; rsync -a . $targethost:$TARGETRAW)

ssh $targethost "bmupdate $ME"

