#!/bin/sh
#
prog=rpi_power
usage="$prog on|up|down|off"
#
#	Power up a (nearly) suspended RPi to activate the network
#	and do stuff.  These actions are reversed by rpi_powerdown.

case $# in
1)	;;
*)	echo "$usage" 1>&2
	exit 1
esac

USBDIR=`ls -d /sys/devices/platform/soc/*.usb`

case "$1" in
up|on)	
#	echo 1 > $USBDIR/buspower	# turn on USB bus
	sudo hciconfig hci up
	;;
down|off)
#	echo 0 > $USBDIR/buspower	# turn off USB bus
	sudo hciconfig hci down	|| exit 20
	;;
*)
	echo "$usage" 1>&2
	exit 2
esac

if false
then
	#ifup wlan0	|| exit 3
	#sudo /etc/init.d/networking start	|| exit 5

	echo -n "prog: awaiting useful network connection." 1>&2
	for count in 6 5 4 3 2 1 0
	do
		echo -n "." 1>&2
		ping -c 2 -w 2 8.8.8.8 >/dev/null 2>/dev/null &&
			break
		if [ $count -eq 0 ]
		then
			echo "$prog: cannot reach the Internet" 1>&2
			exit 10
		fi
		sleep 1
	done
	echo

	echo "$prog: setting time" 1>&2
	ntpdate 3.debian.pool.ntp.org || exit 6
fi

if false
then
	ifdown wlan0

	#echo "$prog: hci" 1>&2
	sudo hciconfig hci down

	# undervoltage indication:
	#echo input | sudo tee /sys/class/leds/led0/trigger

#	USBDIR=`ls -d /sys/devices/platform/soc/*.usb`
	echo 0 > $USBDIR/buspower

#	$LED_OFF
fi
