#!/bin/sh
#
prog=bmespsrv
usage="usage: $prog"
#
#	Network service that receives the Broodminder data from the ESP32. Actually,
#	this will record the harvest of any BLE advertisement.

LOG=/var/log/bledata

if [ ! -f $LOG ]
then
	sudo cp /dev/null $LOG
	sudo chown ches $LOG
fi

exec 2>&1 >>$LOG

rmt=`perl -le 'use Socket; ($port,$addr) = sockaddr_in(getpeername(STDIN)); print inet_ntoa($addr);'`

echo "`date`	`date +%s`	$rmt"
cat -
